name: example
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
permissions:
  # actions: write       # Necessary to cancel workflow executions
  # checks: write        # Necessary to write reports
  # pull-requests: write # Necessary to comment on PRs
  contents: read
  packages: write

on:
  workflow_dispatch:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'

jobs:
  # get_submodules:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4
  #     with:
  #       submodules: 'true'

  #   - name: Store submodule
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: Submodule
  #       path: test_subdir/library

  # ERC:
  #   runs-on: ubuntu-latest
  #   container: setsoft/kicad_auto:latest
  #   needs: get_submodules

  #   steps:
  #   - uses: actions/checkout@v4

  #   - name: Get submodule
  #     uses: actions/download-artifact@v4
  #     with:
  #       name: Submodule
  #       path: test_subdir/library

  #   - name: Run ERC
  #     run: |
  #       make -C test_subdir/ erc

  #   - name: Retrieve results
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: ERC_Output
  #       path: test_subdir/Fabrication

  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    # - name: Get submodule
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: Submodule
    #     path: test_subdir/library
    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        # Required - kibot config file
        config: test_subdir/config.kibot.yaml
        # optional - prefix to output defined in config
        dir: output
        # optional - schematic file
        schema: 'test_subdir/test_subdir.kicad_sch'
        # optional - PCB design file
        board: 'test_subdir/test_subdir.kicad_pcb'

    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: ERC&DRC_Output
        path: test_subdir/Fabrication

    - name: upload results
      uses: actions/upload-artifact@v4
      with:
        name: output
        path: output